// contract v 2.0.1 (3/22/2024): 0x96E7F0a77f2272865e431F6e41B41d580AeEa0eb
EE_ABI = [
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_account",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "Blocked",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_account",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "Composable",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "string",
          name: "_legal",
          type: "string",
        },
      ],
      name: "LegalUpdated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_account",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "Moderator",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_noteReceiver",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "_noteWriter",
          type: "address",
        },
        { indexed: false, internalType: "string", name: "_note", type: "string" },
      ],
      name: "Noted",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_respected",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "_respecter",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "Respected",
      type: "event",
    },
    {
      inputs: [],
      name: "activeEEs",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "allModerators",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleAccountData",
      outputs: [{ internalType: "string[][]", name: "", type: "string[][]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleAdditionalLinks",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleAssociatedAccounts",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleBasicData",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleCustomData",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleNotesReceived",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleNotesSent",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleRespecters",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleRespecting",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "assembleTags",
      outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "blockMyCompromisedAccount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "uint256", name: "_index", type: "uint256" },
      ],
      name: "deleteAdditionalLink",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "uint256", name: "_index", type: "uint256" },
      ],
      name: "deleteAssociatedAccount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "address", name: "_noteAuthor", type: "address" },
      ],
      name: "deleteReceivedNote",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "uint256", name: "_index", type: "uint256" },
      ],
      name: "deleteTag",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "address", name: "_accountLosingNote", type: "address" },
      ],
      name: "deleteWrittenNote",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "getAdditionalLinkTuples",
      outputs: [
        {
          components: [
            { internalType: "string", name: "k", type: "string" },
            { internalType: "string", name: "v", type: "string" },
          ],
          internalType: "struct EtherEthos.StrPair[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "getAssociatedAccountTuples",
      outputs: [
        {
          components: [
            { internalType: "address", name: "k", type: "address" },
            { internalType: "string", name: "v", type: "string" },
          ],
          internalType: "struct EtherEthos.AddrPair[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_respectGiver", type: "address" },
        { internalType: "address", name: "_respectReceiver", type: "address" },
      ],
      name: "giveRespect",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "isComposable",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "legal",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "permissions",
      outputs: [
        { internalType: "bool", name: "composable", type: "bool" },
        { internalType: "bool", name: "accountIsBlocked", type: "bool" },
        { internalType: "bool", name: "moderator", type: "bool" },
        { internalType: "string", name: "verificationResponse", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "ping",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_link", type: "string" },
        { internalType: "string", name: "_detail", type: "string" },
      ],
      name: "pushAdditionalLink",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "address", name: "_associatedAccount", type: "address" },
        { internalType: "string", name: "_detail", type: "string" },
      ],
      name: "pushAssociatedAccount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_tag", type: "string" },
      ],
      name: "pushTag",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "reconcileNotes",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_respectRevoker", type: "address" },
        { internalType: "address", name: "_losingRespect", type: "address" },
      ],
      name: "revokeRespect",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_alias", type: "string" },
      ],
      name: "setAlias",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_custom", type: "string" },
      ],
      name: "setCustomData",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_detail", type: "string" },
      ],
      name: "setDetail",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_gallery", type: "string" },
      ],
      name: "setGallery",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_alias", type: "string" },
        { internalType: "string", name: "_detail", type: "string" },
        { internalType: "string", name: "_socialLink", type: "string" },
        { internalType: "string", name: "_website", type: "string" },
        { internalType: "string", name: "_gallery", type: "string" },
      ],
      name: "setMainBasics",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_noteWriter", type: "address" },
        { internalType: "address", name: "_noteReceiver", type: "address" },
        { internalType: "string", name: "_note", type: "string" },
      ],
      name: "setNote",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "address", name: "_pfpContract", type: "address" },
        { internalType: "uint256", name: "_pfpTokenId", type: "uint256" },
      ],
      name: "setPFP",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "uint8", name: "_priorityLink", type: "uint8" },
      ],
      name: "setPriorityLink",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_socialLink", type: "string" },
      ],
      name: "setSocial",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_verificationResponse", type: "string" },
      ],
      name: "setVerificationResponse",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "string", name: "_website", type: "string" },
      ],
      name: "setWebsite",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "toggleAccountBlock",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "toggleComposable",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_account", type: "address" }],
      name: "toggleModerator",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "uint256", name: "_index", type: "uint256" },
        { internalType: "string", name: "_link", type: "string" },
        { internalType: "string", name: "_detail", type: "string" },
      ],
      name: "updateAdditionalLink",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_account", type: "address" },
        { internalType: "uint256", name: "_index", type: "uint256" },
        { internalType: "address", name: "_associatedAccount", type: "address" },
        { internalType: "string", name: "_detail", type: "string" },
      ],
      name: "updateAssociatedAccount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_delegateContract", type: "address" },
      ],
      name: "updateDelegateContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_legal", type: "string" }],
      name: "updateLegal",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_maxNotesPerAccount", type: "uint256" },
      ],
      name: "updateMaxNotesPerAccount",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ];
  